### ISSUE TITLE
Deleted record visible until "hard" refresh - Ember Data - Firebase

### ISSUE THREAD

**Issue by dominiks** [zoltan-nz/library-app#13]
Hi Zoltan, thanks for this tutorial. I found it very helpful to get started in emberjs while creating my own server backend instead of firebase. I have one problem, though:

1. I open the libraries index in two browser tabs.
2. In one tab I delete a library. The tab stays in the index and the library is gone.
3. The other tab still shows the deleted library when I navigate away from the page and back to it via the navbar. The item only disappears when I refresh the page via F5.

Why does the store still show a deleted item in the list, even after it sends a GET to the server when opening the library index? Or is the response to the DELETE request incomplete when I only send status 200 and an empty json object? I'm using a RESTAdapter for the communication.

p.s. I also posted this as a comment on yoember's disqus but that got caught in a spam filter.

**Comment by zoltan-nz** [comment]
@dominiks Hey Dominiks, thank you.

Great findings and you are right. I noticed the same when I started to play with Firebase. As I see Firebase realtime sync your data when you create a new item, however they don't sync "delete", so it is not realtime... As I see [here, in Firebase doc](https://firebase.google.com/docs/functions/database-events), the official Firebase library supports this option, maybe this is missing from the Emberfire package.

If you built your own server backend, you have to manually setup realtime "websocket" communication.

You can check out this hooks also in Ember Adapter:
https://www.emberjs.com/api/ember-data/3.7/classes/DS.Adapter/methods/shouldReloadAll?anchor=shouldBackgroundReloadAll

You can force your Adapter to reload all the records from the server. So it is always try to find out what is the latest state of your database. Maybe this is only what you need.

Hope this could help, don't hesitate to share your findings and let me know which solution worked. :)
