### ISSUE TITLE
Ember.computed.and   not right

### ISSUE THREAD

**Issue by erwin16** [zoltan-nz/library-app#2]
Thanks for your tutorial ... 

In the Contact Page setup homework, I tried to use the Ember.computed.and property 
I wrote 

      isValid: Ember.computed.match('senderEmailAddress', /^.+@.+\..+$/),
      isNotValid: Ember.computed.not('isValid'),
      isTooShort: Ember.computed.lte('message.length', 4),
     disabled: Ember.computed.and('isNotValid', 'isTooShort'),

so the Send button should be disable when email is invalid and message is too short ..  OK
but the when email is valid OR message is long enough the button is Enabled , it should not

I guess we should use  Ember.computed.or , Send button will be disabled when one of the 2 computed properties is true ..

    disabled: Ember.computed.or('isNotValid', 'isTooShort'),

Isn't it ?

**Comment by zoltan-nz** [comment]
Hi @erwin16, sorry for the late response. (My notification settings was not properly aligned.)

You are totally right, it is mainly depend how do you manage this boolean logic. For example, I used `isMessageEnoughLong` which is the opposite of `isTooShort`. :) So in your case, the `or` will work properly.
