### ISSUE TITLE
Cannot find module 'ember-cli/lib/broccoli/ember-app'`

### ISSUE THREAD

**Issue by jegb** [zoltan-nz/library-app#4]
I am getting this `version: 2.4.1
Could not require 'ember-cli-build.js': Cannot find module 'ember-cli/lib/broccoli/ember-app'`

when I ran $ember server

**Comment by zoltan-nz** [comment]
Hi @jegb, are you still getting this error? Do you have `ember-cli-build.js` in your project folder?

An option could be to delete `bower_components` and `node_modules` from your project and reinstall all the bower packages and node packages with `npm install && bower install`.

**Comment by jegb** [comment]
yes, I fixed it. Seems that I had to move to node 5.5.0, and used nvm. Thanks for the useful project!

**Comment by zoltan-nz** [comment]
@jegb great and thank you. :)

**Comment by bhaveshAn** [comment]
> Seems that I had to move to node 5.5.0, and used nvm. Thanks for the useful project!

@jegb Are you able to run `ember serve`
