### ISSUE TITLE
Not Ember Octane Syntax

### ISSUE THREAD

**Issue by kasunvp** [zoltan-nz/library-app#47]
This is a good repo for a new learner. But...

This app does not implement the new Ember Octane syntax. 

So who might follow this based on the title of this repo will be misguided/misinformed.
Therefore, I think either the syntax should be updated or the title should be changed.  
:-)

Thank you and Good luck!

**Comment by zoltan-nz** [comment]
@kasunvp thanks for message, you totally right. WIP. Changes will be committed soon. :) I keep you posted.

**Comment by zoltan-nz** [comment]
@kasunvp the whole application is updated to Ember Octane syntax. Happy learning! ;)
