### ISSUE TITLE
Books and authors

### ISSUE THREAD

**Issue by jrock2004** [zoltan-nz/library-app#5]
I am wondering if you can expand on your tutorial and show setting up the route for adding a new book? I am trying to expand on this with firebase and having all types of issues

**Comment by sigu** [comment]
@jrock2004 cool. Let me look at how to add this feature with little complexity

**Comment by jrock2004** [comment]
The problem I face is the auto geneterting IDs that firebase does. So I'm looking how you would solve this

**Comment by zoltan-nz** [comment]
Thanks for the suggestion. You can check in the code how we generate books programatically, so based on that, you can extend the logic to create books manually using a form. It is a great homework task. At the moment adding this feature to the tutorial is out of scope, so I close this thread. Thanks.
