### ISSUE TITLE
Using CP-validations instead of comp props on the model?

### ISSUE THREAD

**Issue by QuantumInformation** [zoltan-nz/library-app#8]
Great tut btw!

I think this would bring the app up to date with more real world validation, what do you think?

![image](https://user-images.githubusercontent.com/216566/26973285-a5d5a71c-4d0d-11e7-812c-98ac434fbec2.png)

**Comment by zoltan-nz** [comment]
Hey @QuantumInformation, thank you! :) Yep, I totally agree, cp-validation is an amazing library. However, when you are learning a new framework, better if you practice the "bare metal", so sometimes these abstractions can confuse beginners. It is a great idea to extend the tutorial with more intermediate topics, including with your suggestion. If you play with it and you will have a repository where everybody can check how have you implemented cp-validation, I would add a link to the tutorial as an example, so it would motivate more people to try it out.
