### ISSUE TITLE
What about using closure actions instead of actions?

### ISSUE THREAD

**Issue by QuantumInformation** [zoltan-nz/library-app#9]

**Comment by zoltan-nz** [comment]
Thanks for your suggestion, good point. Yes, closure action is great tool and we use it quite often, so adding a new topic where we talk more about closure action is important. This can be an other new extension to the tutorial. I noticed that the concept of closure action is not easy for beginners, so usually better to add to our toolset in later stage in the learning process. Agree, we need more new topics on www.yoember.com :)
